apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unauthenticated-group-1
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unauthenticated-group-2
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unauthenticated-group-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unauthenticated-group-1
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:unauthenticated
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: unauthenticated-group-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: unauthenticated-group-2
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:unauthenticated
